
friendlycaptcha.sitekey=${FRIENDLYCAPTCHA_SITEKEY:xxxx}
friendlycaptcha.secret=${FRIENDLYCAPTCHA_SECRET:xxxxx}
friendlycaptcha.verify-url=https://global.frcapi.com/api/v2/captcha/siteverify
captcha.enabled=${CAPTCHA_ENABLED:true}
spring.xml.ignore=true
spring.http.converters.preferred-json-mapper=gson
backend.url=${BACKEND_URL:http://localhost:8080}
frontend.url=${FRONTEND_URL:http://localhost:8080}
spring.mail.host=${MAIL_HOST:http://example.com}
spring.mail.port=${MAIL_PORT:25}
spring.mail.password=${MAIL_PASSWORD:xxx}
spring.mail.from=${MAIL_FROM:user}
spring.mail.username=${MAIL_USERNAME:test}
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=INFO
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss.SSS} level=%-5level traceId=%X{traceId} logger=%logger{36} msg=%msg%n"
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST:http://example.com}
esirius.base_url=${ESIRIUS_BASE_URL}
esirius.username=${ESIRIUS_USERNAME:XXXESIRIUS_USERNAMEXXX}
esirius.password=${ESIRIUS_PASSWORD:XXX}
spring.web.resources.static-locations=classpath:/static/
s3.bucket.name=${S3_BUCKET_NAME:XXXS3BUCKETNAME}
s3.endpoint=${S3_ENDPOINT:https://s3.example.test}
s3.access.key=${S3_ACCESS_KEY:XXXS3ACCESSKEY}
s3.secret.key=${S3_SECRET_KEY:XXXS3SECRETKEY}
s3.debug.enabled=${S3_DEBUG_ENABLED:false}
mail.challenge.codeLength=${MAIL_CHALLENGE_CODELENGTH:6}
mail.challenge.codeTtlDays=${MAIL_CHALLENGE_CODETTLDAYS:30}
mail.challenge.maxAttempts=${MAIL_CHALLENGE_MAXATTEMPTS:5}
