export const INCIDENT_FIELDS = {
  VOL: [
    "volDansVehicule",
    "categorieObjet",
    "sousCategorie",
    "typeObjet",
    "fabricant",
    "fabricantAutre",
    "modele",
    "modeleAutre",
    "couleur",
    "couleurSecondaire",
    "numeroCadre",
    "numeroCadreInconnu",
    "vin",
    "vinInconnu",
    "velofinderId",
    "dateAchat",
    "plaqueNumero",
    "plaqueInconnu",
    "plaquePays",
    "plaqueCanton",
    "gravure",
    "valeurReelle",
    "numeroSerie",
    "numeroSerieInconnu",
    "numeroIMEI",
    "numeroIMEIInconnu",
    "justificationAbsenceIMEI",
    "descriptionObjet",
    "objetsVolesValides",
    "avezVousDegradation",
    "adresseLesee",
    "typeLieu",
    "adresseConnue",
    "adresseEvenement",
    "adressePostaleEvenement",
    "npaEvenement",
    "localiteEvenement",
    "paysEvenement",
    "adresseEvenementSecondaire",
    "adressePostaleEvenementSecondaire",
    "npaEvenementSecondaire",
    "localiteEvenementSecondaire",
    "paysEvenementSecondaire",
    "lieuOrigine",
  ],
  DOMMAGE: [
    "typeDommage",
    "objetsDegradesValides",
    "sousCategorie",
    "typeObjet",
    "fabricant",
    "fabricantAutre",
    "modele",
    "modeleAutre",
    "couleur",
    "couleurSecondaire",
    "numeroCadre",
    "numeroCadreInconnu",
    "vin",
    "vinInconnu",
    "velofinderId",
    "dateAchat",
    "plaqueNumero",
    "plaqueInconnu",
    "plaquePays",
    "plaqueCanton",
    "montantEstime",
    "devise",
    "naturesDommage",
    "description",
    "constatPresent",
    "dateConstat",
    "adresseConnue",
    "adresseLesee",
    "adresseEvenement",
    "adressePostaleEvenement",
    "npaEvenement",
    "localiteEvenement",
    "paysEvenement",
    "typeLieu",
    "lieuOrigine",
    "adresseEvenementSecondaire",
    "adressePostaleEvenementSecondaire",
    "npaEvenementSecondaire",
    "localiteEvenementSecondaire",
    "paysEvenementSecondaire",
  ],
  CYBERCRIME: [
    "typeCybercrime",
    "descriptionCybercrime",
  ],
} as const;

export type IncidentKey = keyof typeof INCIDENT_FIELDS;

export const INCIDENT_TYPE_MAP: Record<string, IncidentKey> = {
  vol: "VOL",
  "degat-delit": "DOMMAGE",
  cybercrime: "CYBERCRIME",
};
