CH_GE_OCSIN_IMAGE_APPLICATION=11729_ppel
BUILDAH_BUILD_ARG_FILE=.buildah-build-args.conf
: "${OCI_CATALOG_HOST:?OCI_CATALOG_HOST is required}"
printf 'OCI_CATALOG_HOST=%s\n' "$OCI_CATALOG_HOST" > "$BUILDAH_BUILD_ARG_FILE"
ORG_OPENCONTAINERS_IMAGE_TITLE='Pre-plainte en ligne back-end'
ORG_OPENCONTAINERS_IMAGE_BASE_NAME=${OCI_CATALOG_HOST}/ch/ge/common/middlewares/java/ubi9-openjdk21:4.0.1-20250715_121737
