sonar.java.binaries=pre-plainte-core/target/classes,pre-plainte-infrastructure/target/classes,pre-plainte-rest/target/classes
sonar.javascript.globals=cy,Cypress
sonar.typescript.tsconfigPaths=pre-plainte-ihm/tsconfig.json
sonar.exclusions=pre-plainte-cypress/**
sonar.coverage.exclusions=pre-plainte-ihm/**,pre-plainte-cypress/**,**/*Test.java,**/ech051/dto/**
sonar.coverage.jacoco.xmlReportPaths=pre-plainte-core/target/site/jacoco/jacoco.xml,pre-plainte-infrastructure/target/site/jacoco/jacoco.xml,pre-plainte-rest/target/site/jacoco/jacoco.xml
