import type { PrePlainteFormFields } from "@/types/pre-plainte.interface";
import { RIPOL } from "@/constants/constant";

/**
 * Structure de données initiale pour le formulaire de pré-plainte
 * Contient tous les champs avec leurs valeurs par défaut
 */
export const getInitialFormData = (): PrePlainteFormFields => ({
  /* Informations générales */
  confirmeIdentite: false,
  confirmeSituation: false,

  /* Informations personnelles */
  lienAvecPersonne: "",
  typeRepresentation: "",
  postePersonneMorale: "",
  justificatifPersonneMorale: [],

  /* Déclarant */
  nom: "",
  nomNaissance: "",
  prenom: "",
  genre: null,
  nationalite: null,
  dateNaissance: "",
  adresse: "",
  adressePostale: "",
  npa: "",
  localite: "",
  pays: RIPOL.PAYS_SUISSE,
  titreSejour: "",
  telephone: "",
  email: "",
  confirmationEmail: "",
  typeDocumentIdentite: "",
  numeroDocumentIdentite: "",

  /* Tiers */
  tiersNom: "",
  tiersPrenom: "",
  tiersGenre: null,
  tiersNationalite: null,
  tiersDateNaissance: "",
  tiersAdresse: "",
  tiersAdressePostale: "",
  tiersNpa: "",
  tiersLocalite: "",
  tiersPays: RIPOL.PAYS_SUISSE,
  tiersTelephone: "",
  tiersEmail: "",
  tiersConfirmationEmail: "",
  tiersTypeDocumentIdentite: "",
  tiersNumeroDocumentIdentite: "",

  /* Organisation */
  organisationNom: "",
  organisationAdresse: "",
  organisationAdressePostale: "",
  organisationNpa: "",
  organisationLocalite: "",
  organisationPays: RIPOL.PAYS_SUISSE,
  organisationTelephone: "",
  organisationEmail: "",
  organisationConfirmationEmail: "",

  /* Incident */
  typeIncident: "",
  dateDebutEvenement: "",
  heureDebutEvenement: "",
  dateFinEvenement: "",
  heureFinEvenement: "",

  /* Commun vol & dommage */
  adresseLesee: null,
  typeLieu: null,
  adresseConnue: null,
  adresseEvenement: "",
  adressePostaleEvenement: "",
  npaEvenement: "",
  localiteEvenement: "",
  paysEvenement: RIPOL.PAYS_SUISSE,
  lieuOrigine: null,
  isTrajet: null,
  adresseEvenementSecondaire: "",
  adressePostaleEvenementSecondaire: "",
  npaEvenementSecondaire: "",
  localiteEvenementSecondaire: "",
  paysEvenementSecondaire: RIPOL.PAYS_SUISSE,

  sousCategorie: "",
  typeObjet: null,
  fabricant: null,
  fabricantAutre: "",
  modele: null,
  modeleAutre: "",
  couleur: null,
  couleurSecondaire: null,
  numeroCadre: "",
  numeroCadreInconnu: false,
  vin: "",
  vinInconnu: false,
  velofinderId: "",
  dateAchat: "",
  plaqueNumero: "",
  plaqueInconnu: false,
  plaquePays: null,
  plaqueCanton: null,
  assuranceAucune: false,
  assureur: null,
  assureurAutre: "",
  numeroAssurance: "",
  numeroVignette: "",
  numeroMaster: "",

  fichiers: [],

  /* Vol */
  volDansVehicule: null,
  categorieObjet: "",
  gravure: "",
  valeurReelle: "",
  numeroSerie: "",
  numeroSerieInconnu: false,
  numeroIMEI: "",
  numeroIMEIInconnu: false,
  justificationAbsenceIMEI: "",
  isVehicle: false,
  avezVousDegradation: null,
  objetsVolesValides: [],

  /* Dommage */
  typeDommage: "",
  montantEstime: "",
  devise: "",
  naturesDommage: [],
  description: "",
  constatPresent: null,
  dateConstat: "",
  objetsDegradesValides: [],

  /* Cybercrime commun */
  typeCybercrime: "",
  autresDocuments: [],

  /* Commun commande frauduleuse & fausse annonce */
  descriptionCybercrime: "",
  justificatifsPaiement: [],
  copiesEcran: [],

  /* Commun achat non reçu & fausse annonce */
  datePremierContact: "",
  heurePremierContact: "",
  dateDernierContact: "",
  heureDernierContact: "",

  /* Commande frauduleuse */
  prestataire: "",
  dateDecouverte: "",
  montant: "",
  assurance: null,
  emailCommandeInconnu: false,
  emailCommande: "",
  telephoneCommandeInconnu: false,
  telephoneCommande: "",
  livraisonAdresseLesee: null,
  livraisonAdresse: "",
  livraisonAdressePostale: "",
  livraisonNpa: "",
  livraisonLocalite: "",
  livraisonLocaliteCode: "",
  livraisonPays: "",

  /* Achat non reçu */
  montantDelitAchatLigne: "",
  articleNonLivreDescription: "",
  prenomVendeur: "",
  nomVendeur: "",
  telephoneVendeurInconnu: false,
  telephoneVendeur: "",
  emailVendeurInconnu: false,
  emailVendeur: "",
  adresseVendeurInconnue: false,
  vendeurAdresse: "",
  vendeurAdressePostale: "",
  vendeurNpa: "",
  vendeurLocalite: "",
  vendeurLocaliteCode: "",
  vendeurPays: "",
  achatViaPlaceMarche: null,
  plateforme: "",
  plateformeAutre: "",
  plateformeId: "",
  nomEntrepriseVendeur: "",
  siteWebEntrepriseVendeur: "",
  annonceDocument: [],
  annonceDocumentIndisponible: false,
  raisonAbsenceAnnonce: "",
  moyenPaiement: "",
  moyenPaiementAutre: "",
  ibanBeneficiaire: "",
  comptePaypalBeneficiaire: "",
  numeroTwintBeneficiaire: "",
  adresseWalletCrypto: "",
  hashTransactionCrypto: "",
  societeBeneficiaire: "",
  nomBeneficiaire: "",
  prenomBeneficiaire: "",
  dateOperation: "",
  preuvePaiementDocument: [],
  preuvePaiementIndisponible: false,
  raisonAbsencePreuvePaiement: "",
  copieIdentiteTransmiseAuteur: null,
  copieIdentiteTransmiseAuteurDocument: [],
  copieIdentiteAuteurTransmise: null,
  copieIdentiteAuteurDocument: [],

  /* Fausse annonce */
  urlComplete: "",
  titreAnnonce: "",
  nomBailleur: "",
  emailBailleurInconnu: false,
  emailBailleur: "",
  telephoneBailleurInconnu: false,
  telephoneBailleur: "",
  adresseBienImmobilier: "",
  montantDemande: "",
  modePaiementDemande: "",

  /* Rendez-vous */
  preferenceRendezVous: "",
  dateSouhaitee: "",
  creneauPrefere: "",
  dateAlternative: "",
  commentairesRendezVous: "",
  modeContactPrefere: "",
  codeRdv: "",
  selectedCreneau: null,

});
