import type { PrePlainteFormFields } from "@/types/pre-plainte.interface";
import { RIPOL } from "@/constants/constant";

type InitialFormDataPart = Partial<PrePlainteFormFields>;

const getIdentityInitialData = (): InitialFormDataPart => ({
  confirmeIdentite: false,
  confirmeSituation: false,
  lienAvecPersonne: "",
  typeRepresentation: "",
  postePersonneMorale: "",
  justificatifPersonneMorale: [],
  nom: "",
  nomNaissance: "",
  prenom: "",
  genre: null,
  nationalite: null,
  dateNaissance: "",
  adresse: "",
  adressePostale: "",
  npa: "",
  localite: "",
  pays: RIPOL.PAYS_SUISSE,
  titreSejour: "",
  telephone: "",
  email: "",
  confirmationEmail: "",
  typeDocumentIdentite: "",
  numeroDocumentIdentite: "",
  tiersNom: "",
  tiersPrenom: "",
  tiersGenre: null,
  tiersNationalite: null,
  tiersDateNaissance: "",
  tiersAdresse: "",
  tiersAdressePostale: "",
  tiersNpa: "",
  tiersLocalite: "",
  tiersPays: RIPOL.PAYS_SUISSE,
  tiersTelephone: "",
  tiersEmail: "",
  tiersConfirmationEmail: "",
  tiersTypeDocumentIdentite: "",
  tiersNumeroDocumentIdentite: "",
  organisationNom: "",
  organisationAdresse: "",
  organisationAdressePostale: "",
  organisationNpa: "",
  organisationLocalite: "",
  organisationPays: RIPOL.PAYS_SUISSE,
  organisationTelephone: "",
  organisationEmail: "",
  organisationConfirmationEmail: "",
});

const getIncidentInitialData = (): InitialFormDataPart => ({
  typeIncident: "",
  dateDebutEvenement: "",
  heureDebutEvenement: "",
  dateFinEvenement: "",
  heureFinEvenement: "",
  adresseLesee: null,
  typeLieu: null,
  adresseConnue: null,
  adresseEvenement: "",
  adressePostaleEvenement: "",
  npaEvenement: "",
  localiteEvenement: "",
  paysEvenement: RIPOL.PAYS_SUISSE,
  lieuOrigine: null,
  isTrajet: null,
  adresseEvenementSecondaire: "",
  adressePostaleEvenementSecondaire: "",
  npaEvenementSecondaire: "",
  localiteEvenementSecondaire: "",
  paysEvenementSecondaire: RIPOL.PAYS_SUISSE,
  sousCategorie: "",
  typeObjet: null,
  fabricant: null,
  fabricantAutre: "",
  modele: null,
  modeleAutre: "",
  couleur: null,
  couleurSecondaire: null,
  numeroCadre: "",
  numeroCadreInconnu: false,
  vin: "",
  vinInconnu: false,
  velofinderId: "",
  dateAchat: "",
  plaqueNumero: "",
  plaqueInconnu: false,
  plaquePays: null,
  plaqueCanton: null,
  assuranceAucune: false,
  assureur: null,
  assureurAutre: "",
  numeroAssurance: "",
  numeroVignette: "",
  numeroMaster: "",
  fichiers: [],
});

const getVolDommageInitialData = (): InitialFormDataPart => ({
  volDansVehicule: null,
  categorieObjet: "",
  gravure: "",
  valeurReelle: "",
  numeroSerie: "",
  numeroSerieInconnu: false,
  numeroIMEI: "",
  numeroIMEIInconnu: false,
  justificationAbsenceIMEI: "",
  isVehicle: false,
  avezVousDegradation: null,
  objetsVolesValides: [],
  typeDommage: "",
  montantEstime: "",
  devise: "",
  naturesDommage: [],
  description: "",
  constatPresent: null,
  dateConstat: "",
  objetsDegradesValides: [],
});

const getCybercrimeInitialData = (): InitialFormDataPart => ({
  typeCybercrime: "",
  autresDocuments: [],
  descriptionCybercrime: "",
  justificatifsPaiement: [],
  copiesEcran: [],
  datePremierContact: "",
  heurePremierContact: "",
  dateDernierContact: "",
  heureDernierContact: "",
  prestataire: "",
  dateDecouverte: "",
  montant: "",
  assurance: null,
  emailCommandeInconnu: false,
  emailCommande: "",
  telephoneCommandeInconnu: false,
  telephoneCommande: "",
  livraisonAdresseLesee: null,
  livraisonAdresse: "",
  livraisonAdressePostale: "",
  livraisonNpa: "",
  livraisonLocalite: "",
  livraisonLocaliteCode: "",
  livraisonPays: "",
  prenomContrevenant: "",
  nomContrevenant: "",
  siteWebContrevenant: "",
  contrevenantAdresse: "",
  contrevenantAdressePostale: "",
  contrevenantNpa: "",
  contrevenantLocalite: "",
  contrevenantLocaliteCode: "",
  contrevenantPays: "",
  moyenPaiementNumeriqueDebite: null,
  montantDelitAchatLigne: "",
  articleNonLivreDescription: "",
  prenomVendeur: "",
  nomVendeur: "",
  telephoneVendeurInconnu: false,
  telephoneVendeur: "",
  emailVendeurInconnu: false,
  emailVendeur: "",
  adresseVendeurInconnue: false,
  vendeurAdresse: "",
  vendeurAdressePostale: "",
  vendeurNpa: "",
  vendeurLocalite: "",
  vendeurLocaliteCode: "",
  vendeurPays: "",
  achatViaPlaceMarche: null,
  plateforme: "",
  plateformeAutre: "",
  plateformeId: "",
  nomEntrepriseVendeur: "",
  siteWebEntrepriseVendeur: "",
  annonceDocument: [],
  annonceDocumentIndisponible: false,
  raisonAbsenceAnnonce: "",
  moyenPaiement: "",
  moyenPaiementAutre: "",
  ibanBeneficiaire: "",
  comptePaypalBeneficiaire: "",
  numeroTransactionPaypal: "",
  numeroTwintBeneficiaire: "",
  typeCryptoMonnaie: "",
  montantUnitesCrypto: "",
  adresseWalletExpediteur: "",
  adresseWalletCrypto: "",
  hashTransactionCrypto: "",
  societeBeneficiaire: "",
  nomBeneficiaire: "",
  prenomBeneficiaire: "",
  dateOperation: "",
  preuvePaiementDocument: [],
  preuvePaiementIndisponible: false,
  raisonAbsencePreuvePaiement: "",
  copieIdentiteTransmiseAuteur: null,
  copieIdentiteTransmiseAuteurDocument: [],
  copieIdentiteTransmiseAuteurDocumentIndisponible: false,
  raisonAbsenceCopieIdentiteTransmiseAuteur: "",
  copieIdentiteAuteurTransmise: null,
  copieIdentiteAuteurDocument: [],
  copieIdentiteAuteurDocumentIndisponible: false,
  raisonAbsenceCopieIdentiteAuteur: "",
  urlComplete: "",
  titreAnnonce: "",
  nomBailleur: "",
  emailBailleurInconnu: false,
  emailBailleur: "",
  telephoneBailleurInconnu: false,
  telephoneBailleur: "",
  adresseBienImmobilier: "",
  montantDemande: "",
  modePaiementDemande: "",
});

const getRendezVousInitialData = (): InitialFormDataPart => ({
  preferenceRendezVous: "",
  dateSouhaitee: "",
  creneauPrefere: "",
  dateAlternative: "",
  commentairesRendezVous: "",
  modeContactPrefere: "",
  codeRdv: "",
  selectedCreneau: null,
});

export const getInitialFormData = (): PrePlainteFormFields =>
  ({
    ...getIdentityInitialData(),
    ...getIncidentInitialData(),
    ...getVolDommageInitialData(),
    ...getCybercrimeInitialData(),
    ...getRendezVousInitialData(),
  }) as PrePlainteFormFields;
